//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.BusinessTrip.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SelectedUser {
            get {
                return ((bool)(this["SelectedUser"]));
            }
            set {
                this["SelectedUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SortIndexPersons {
            get {
                return ((int)(this["SortIndexPersons"]));
            }
            set {
                this["SortIndexPersons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SortOrderPersons {
            get {
                return ((bool)(this["SortOrderPersons"]));
            }
            set {
                this["SortOrderPersons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SortIndexBusinessTrips {
            get {
                return ((int)(this["SortIndexBusinessTrips"]));
            }
            set {
                this["SortIndexBusinessTrips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SortOrderBusinessTrips {
            get {
                return ((bool)(this["SortOrderBusinessTrips"]));
            }
            set {
                this["SortOrderBusinessTrips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SortIndexDepartments {
            get {
                return ((int)(this["SortIndexDepartments"]));
            }
            set {
                this["SortIndexDepartments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SortOrderDepartments {
            get {
                return ((bool)(this["SortOrderDepartments"]));
            }
            set {
                this["SortOrderDepartments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SortIndexLocations {
            get {
                return ((int)(this["SortIndexLocations"]));
            }
            set {
                this["SortIndexLocations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SortOrderLocations {
            get {
                return ((bool)(this["SortOrderLocations"]));
            }
            set {
                this["SortOrderLocations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SortIndexOrganizations {
            get {
                return ((int)(this["SortIndexOrganizations"]));
            }
            set {
                this["SortIndexOrganizations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SortOrderOrganizations {
            get {
                return ((bool)(this["SortOrderOrganizations"]));
            }
            set {
                this["SortOrderOrganizations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SortIndexPartys {
            get {
                return ((int)(this["SortIndexPartys"]));
            }
            set {
                this["SortIndexPartys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SortOrderPartys {
            get {
                return ((bool)(this["SortOrderPartys"]));
            }
            set {
                this["SortOrderPartys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SortIndexPositions {
            get {
                return ((int)(this["SortIndexPositions"]));
            }
            set {
                this["SortIndexPositions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SortOrderPositions {
            get {
                return ((bool)(this["SortOrderPositions"]));
            }
            set {
                this["SortOrderPositions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SortIndexTransports {
            get {
                return ((int)(this["SortIndexTransports"]));
            }
            set {
                this["SortIndexTransports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SortOrderTransports {
            get {
                return ((bool)(this["SortOrderTransports"]));
            }
            set {
                this["SortOrderTransports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SortIndexTypeWorks {
            get {
                return ((int)(this["SortIndexTypeWorks"]));
            }
            set {
                this["SortIndexTypeWorks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SortOrderTypeWorks {
            get {
                return ((bool)(this["SortOrderTypeWorks"]));
            }
            set {
                this["SortOrderTypeWorks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("645")]
        public int WindowWidthViewPersons {
            get {
                return ((int)(this["WindowWidthViewPersons"]));
            }
            set {
                this["WindowWidthViewPersons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("405")]
        public int WindowHeightViewPersons {
            get {
                return ((int)(this["WindowHeightViewPersons"]));
            }
            set {
                this["WindowHeightViewPersons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WindowStateMaximizedViewPersons {
            get {
                return ((bool)(this["WindowStateMaximizedViewPersons"]));
            }
            set {
                this["WindowStateMaximizedViewPersons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("645")]
        public int WindowWidthViewTypeWorks {
            get {
                return ((int)(this["WindowWidthViewTypeWorks"]));
            }
            set {
                this["WindowWidthViewTypeWorks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("645")]
        public int WindowWidthViewTransports {
            get {
                return ((int)(this["WindowWidthViewTransports"]));
            }
            set {
                this["WindowWidthViewTransports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("645")]
        public int WindowWidthViewPositions {
            get {
                return ((int)(this["WindowWidthViewPositions"]));
            }
            set {
                this["WindowWidthViewPositions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("645")]
        public int WindowWidthViewPartys {
            get {
                return ((int)(this["WindowWidthViewPartys"]));
            }
            set {
                this["WindowWidthViewPartys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("645")]
        public int WindowWidthViewOrganizations {
            get {
                return ((int)(this["WindowWidthViewOrganizations"]));
            }
            set {
                this["WindowWidthViewOrganizations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("645")]
        public int WindowWidthViewLocations {
            get {
                return ((int)(this["WindowWidthViewLocations"]));
            }
            set {
                this["WindowWidthViewLocations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int WindowWidthViewDirections {
            get {
                return ((int)(this["WindowWidthViewDirections"]));
            }
            set {
                this["WindowWidthViewDirections"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("645")]
        public int WindowWidthViewDepartments {
            get {
                return ((int)(this["WindowWidthViewDepartments"]));
            }
            set {
                this["WindowWidthViewDepartments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("860")]
        public int WindowWidthViewBusinessTrips {
            get {
                return ((int)(this["WindowWidthViewBusinessTrips"]));
            }
            set {
                this["WindowWidthViewBusinessTrips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("310")]
        public int WindowHeightViewTypeWorks {
            get {
                return ((int)(this["WindowHeightViewTypeWorks"]));
            }
            set {
                this["WindowHeightViewTypeWorks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("310")]
        public int WindowHeightViewTransports {
            get {
                return ((int)(this["WindowHeightViewTransports"]));
            }
            set {
                this["WindowHeightViewTransports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("275")]
        public int WindowHeightViewPositions {
            get {
                return ((int)(this["WindowHeightViewPositions"]));
            }
            set {
                this["WindowHeightViewPositions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("385")]
        public int WindowHeightViewPartys {
            get {
                return ((int)(this["WindowHeightViewPartys"]));
            }
            set {
                this["WindowHeightViewPartys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("310")]
        public int WindowHeightViewOrganizations {
            get {
                return ((int)(this["WindowHeightViewOrganizations"]));
            }
            set {
                this["WindowHeightViewOrganizations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("335")]
        public int WindowHeightViewLocations {
            get {
                return ((int)(this["WindowHeightViewLocations"]));
            }
            set {
                this["WindowHeightViewLocations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("239")]
        public int WindowHeightViewDirections {
            get {
                return ((int)(this["WindowHeightViewDirections"]));
            }
            set {
                this["WindowHeightViewDirections"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("310")]
        public int WindowHeightViewDepartments {
            get {
                return ((int)(this["WindowHeightViewDepartments"]));
            }
            set {
                this["WindowHeightViewDepartments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("944")]
        public int WindowHeightViewBusinessTrips {
            get {
                return ((int)(this["WindowHeightViewBusinessTrips"]));
            }
            set {
                this["WindowHeightViewBusinessTrips"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WindowStateMaximizedViewTypeWorks {
            get {
                return ((bool)(this["WindowStateMaximizedViewTypeWorks"]));
            }
            set {
                this["WindowStateMaximizedViewTypeWorks"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WindowStateMaximizedViewTransports {
            get {
                return ((bool)(this["WindowStateMaximizedViewTransports"]));
            }
            set {
                this["WindowStateMaximizedViewTransports"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WindowStateMaximizedViewPositions {
            get {
                return ((bool)(this["WindowStateMaximizedViewPositions"]));
            }
            set {
                this["WindowStateMaximizedViewPositions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WindowStateMaximizedViewPartys {
            get {
                return ((bool)(this["WindowStateMaximizedViewPartys"]));
            }
            set {
                this["WindowStateMaximizedViewPartys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WindowStateMaximizedViewOrganizations {
            get {
                return ((bool)(this["WindowStateMaximizedViewOrganizations"]));
            }
            set {
                this["WindowStateMaximizedViewOrganizations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WindowStateMaximizedViewLocations {
            get {
                return ((bool)(this["WindowStateMaximizedViewLocations"]));
            }
            set {
                this["WindowStateMaximizedViewLocations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WindowStateMaximizedViewDirections {
            get {
                return ((bool)(this["WindowStateMaximizedViewDirections"]));
            }
            set {
                this["WindowStateMaximizedViewDirections"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WindowStateMaximizedViewDepartments {
            get {
                return ((bool)(this["WindowStateMaximizedViewDepartments"]));
            }
            set {
                this["WindowStateMaximizedViewDepartments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WindowStateMaximizedViewBusinessTrips {
            get {
                return ((bool)(this["WindowStateMaximizedViewBusinessTrips"]));
            }
            set {
                this["WindowStateMaximizedViewBusinessTrips"] = value;
            }
        }
    }
}
