// <auto-generated />
namespace Core.BusinessTrip.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ShortAddressRequiredLength250 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShortAddressRequiredLength250));
        
        string IMigrationMetadata.Id
        {
            get { return "201809120851059_ShortAddressRequiredLength250"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
